language: node_js
node_js:
- '6'
sudo: false
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
before_script:
- export DISPLAY=:99.0
- export BRANCH_NAME=$TRAVIS_BRANCH
- export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
- sh -e /etc/init.d/xvfb start
- npm install pm2 -g
- npm run start-prod-api
- npm run start-prod
script:
- npm run lint
- npm test
- npm run test-node
- npm run test-ui
- pm2 kill
after_failure:
- pm2 kill
notifications:
  slack: lits-devops-group1:RZl5uiQeW2Gxnn4ZXONaEW8V
before_deploy:
- echo $TRAVIS_COMMIT > .commit-hash
- make create-dist
deploy:
- provider: s3
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: &1
    secure: yUE7un+wYDwwCQPXIsosjFreOk2AZphvBlWt1hpxadDtsTOkwApHoRMv9KlpAeuTh3AywaYxYfGCEm5aO3CE5Cj3uJ2ieKG1M+/JPuLDwLNBdaCQT3P5ebGDIvfjgDBR2CghFPqZTIKPpqVXmvR96r7mamPhmQtSCpfzip61FOV9mkP1f1nDmq4aD8TRH6x7ZN5ARPmV+9CWGJ1CLXZGbSdOhSLV3en6+EJdkJ5I0RnsM/g50k/V3W+7F+hszYUaRZxl7Qc88QQi/3XdtADQRPLo2qqzZSKonriSlHcKKPtAkzfizOwjS6UgcQGJgxCBuAvdzHudPfYkOrozjW0kYZTHCsoVJqSJtS5sVhQ2pvzJ+r+LDrA3rNFq8Up+uliuxDeSDktJGpiiGSeR1l1N6N43yXH9bk21DfLM6NBUjWN6Hq2YtJC7uJ9ybTzfDRy7Yxx32pLfFeiZXFi1He4HVvy9qaDHWmwh0sWL/7Ue/Xr+r5gPya9Measha6IB3nOPZD+BXSXVuJ2wveYDUVgW95CnP5UaKrs9sx82LcB/1FpeNU0mGTV8M1nvULLBVZ0+gltsqe6tvB6HIv3vUmWt/3rilLoOVlGijV1ymuKRZV2uMQ8HLT85QuccVsdThK+5sAZOoE1SXFsPLtGF+tu/sAJqeSRfw5Dz68LWvwR9/vY=
  bucket: lits-devops1
  skip_cleanup: true
  local_dir: build
  upload-dir: deployments
  region: eu-west-1
  on: &2
    branch: master
- provider: codedeploy
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  key: deployments/app-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.tar.gz
  application: LITS-DevOps
  deployment_group: Prod
  region: eu-west-1
  on: *2
  bundle_type: tgz
- provider: s3
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  skip_cleanup: true
  local_dir: build
  upload-dir: deployments
  region: eu-west-1
  on: &3
    branch: release*
- provider: codedeploy
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  key: deployments/app-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.tar.gz
  application: LITS-DevOps
  deployment_group: Staging
  region: eu-west-1
  on: *3
  bundle_type: tgz
- provider: s3
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  skip_cleanup: true
  local_dir: build
  upload-dir: deployments
  region: eu-west-1
  on: &4
    branch: develop
- provider: codedeploy
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  key: deployments/app-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.tar.gz
  application: LITS-DevOps
  deployment_group: Dev
  region: eu-west-1
  on: *4
  bundle_type: tgz
env:
  global:
  - secure: vko1krrkzJvrveYcWJ+RODpwvqive3/nXK50ZhDFOaXb/eizYM/LgtHpDwfSNROfyPC5VI/6Hwc/5vylj/iP87s+CQfQqQaYpd4VCpaw5n9nPMyCBILsroDZzMnchynGA52/D7lAb9S2e7E3tiU2Kly+3hFg2d+MDyHsg3zclp6Lu9cvEcPN+nZ+qxQrRD7hEnkjA7/EXG+T8aSZVbKJuowXXDf2MXrSFE1Qt52jlB0MY/7FhZHuRWk+2n1BbI0bPG479/2stUlVaMwHH1szxHxO1TkeqZigLSSUxuLvcdGKDVF4wSHESw2exT4ZWmHMQSx+rXrBBxIpFUKidXc0DVThSra2yJH/SB6lIC794NFBC82LU4Hp4qcT2tTUB6E9+/WqRUmdjpPVCnUL6EaLi21nhlKzJ1IOvGQQ4Omu944rJH+zJlOYuk3MPAaaq1Kbjl4Rc0U7zPLNi2NU2H+nqCh0XzZJyCS/rAO+AZubBu6Rb3Zd+9L9JVndP8heoUyWmb1DXy7D66DoFL5eol05rfbsE1mbfiWwkICEYqkkmY45hDTiGcqlsYG2++en2eC/Bcb62L0qCJew4xquuP+lXsUfOQZ326WdMexxhQ6BE1UFj7Y7AMtm6PvZ0xWH7BePquMC9muabXI+CF9qjlwYEznJ1+KsL3bcBSLm/J6Rivk=
  - secure: ix3oA9Ig/lyGArjkqiCvpTkXCxdEw1eCpUS6J/3dHHr7Fk9z2poHSwdS6HMEQ1EVzI2Lbzf91wkoRN45PZ7Aw11ryMLnREK5wcNrwlFpHP9qVFbw0sjLAN3A62/CG1GHZWRuoyoWNq+ncK8d/1owJiRD8isLRLd8rXrr8O/88kWFP7nZu+dQLyoaen26gBFSB4Dp0l+LtSRyl3BnbgWDlbutCmF3Y6CcU4CMm/UIuWjipaGdZy/aa1u53005X3HQDZM904VKnM+wS0gLPoOFMJxInOyhYwUbUqXK23ve0K1ytMTFIGJuhw/iwRqrX70IwZfcVFnFNIcnClYoKze+0y1l+IDQnaFSuO23FNWCgpO5IB6fmrBmcRQlP7rwvhgKbZFQHIkjQ9bspT9BF0TVLOW7k0aAEXzPmkmlf3x7GiNkJPSJ8JlofyfelVqhT8sqxzaL14edDpkrkRpI+yTBfZS1lvY5+JyI6klMWhEECXLVLs1kYelvS6uvf5b714+BpvfeYTQ3mU45KA+EbtnvyGli/YoyZ1YFq2lyV2lc7HknlEdZRPc9nfId6C5wSJDilxq0x6Kh4O0p/J4PFRsazo3pzxL8oe/yZJRZ/V4Jw7w61iVGSpvbtd1YWbndMzoZLM8aWR+ODKLM1h5tnWIXx/3VBFcVCBbQhbudWn0nLWE=
