language: node_js
node_js:
- '6'
sudo: false
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- npm install pm2 -g
- npm install casperjs -g
- pm2 kill
before_script:
- export DISPLAY=:99.0
- export BRANCH_NAME=$TRAVIS_BRANCH
- export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
- sh -e /etc/init.d/xvfb start
- npm run build
- npm run start-prod-api
- npm run start-prod
script:
- npm run lint
- npm test
- npm run test-node
- npm run test-ui-reference
after_failure:
- pm2 kill
notifications:
  slack: lits-devops-group1:RZl5uiQeW2Gxnn4ZXONaEW8V
before_deploy:
- pm2 kill
- echo $TRAVIS_COMMIT > .commit-hash
- make create-dist
deploy:
- provider: s3
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: &1
    secure: yUE7un+wYDwwCQPXIsosjFreOk2AZphvBlWt1hpxadDtsTOkwApHoRMv9KlpAeuTh3AywaYxYfGCEm5aO3CE5Cj3uJ2ieKG1M+/JPuLDwLNBdaCQT3P5ebGDIvfjgDBR2CghFPqZTIKPpqVXmvR96r7mamPhmQtSCpfzip61FOV9mkP1f1nDmq4aD8TRH6x7ZN5ARPmV+9CWGJ1CLXZGbSdOhSLV3en6+EJdkJ5I0RnsM/g50k/V3W+7F+hszYUaRZxl7Qc88QQi/3XdtADQRPLo2qqzZSKonriSlHcKKPtAkzfizOwjS6UgcQGJgxCBuAvdzHudPfYkOrozjW0kYZTHCsoVJqSJtS5sVhQ2pvzJ+r+LDrA3rNFq8Up+uliuxDeSDktJGpiiGSeR1l1N6N43yXH9bk21DfLM6NBUjWN6Hq2YtJC7uJ9ybTzfDRy7Yxx32pLfFeiZXFi1He4HVvy9qaDHWmwh0sWL/7Ue/Xr+r5gPya9Measha6IB3nOPZD+BXSXVuJ2wveYDUVgW95CnP5UaKrs9sx82LcB/1FpeNU0mGTV8M1nvULLBVZ0+gltsqe6tvB6HIv3vUmWt/3rilLoOVlGijV1ymuKRZV2uMQ8HLT85QuccVsdThK+5sAZOoE1SXFsPLtGF+tu/sAJqeSRfw5Dz68LWvwR9/vY=
  bucket: lits-devops1
  skip_cleanup: true
  local_dir: build
  upload-dir: deployments
  region: eu-west-1
  on: &2
    branch: master
- provider: s3
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  skip_cleanup: false
  local_dir: pixel-perfect/references/
  upload-dir: references
  region: eu-west-1
  on:
    branch: feature/backstop
- provider: codedeploy
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  key: deployments/app-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.tar.gz
  application: LITS-DevOps
  deployment_group: Prod
  region: eu-west-1
  on: *2
  bundle_type: tgz
- provider: s3
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  skip_cleanup: true
  local_dir: build
  upload-dir: deployments
  region: eu-west-1
  on: &3
    branch: release*
- provider: codedeploy
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  key: deployments/app-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.tar.gz
  application: LITS-DevOps
  deployment_group: Staging
  region: eu-west-1
  on: *3
  bundle_type: tgz
- provider: s3
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  skip_cleanup: true
  local_dir: build
  upload-dir: deployments
  region: eu-west-1
  on: &4
    branch: develop
- provider: codedeploy
  access_key_id: AKIAIGA6MGVKK7QE2HIA
  secret_access_key: *1
  bucket: lits-devops1
  key: deployments/app-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH.tar.gz
  application: LITS-DevOps
  deployment_group: Dev
  region: eu-west-1
  on: *4
  bundle_type: tgz
env:
  global:
    secure: Z2gtI4SP2vPSr4U/Kf5Q7XHIzfTijr8gTZrRU6JHzr7u7Y2WfHqSMV9pt03a3AGlVKDtdyGLQY9k27e1ysVyIu1zlEmhXvv7aje3pPrpX9cGq8vEd9lku4SxvkWljqo+0Nv13cajIv5sYs9fo24wzsomBSNaMOt3pjFG0w/0++Vmz2+3dz5sqj8NHhd4AWx19fHIIbOa4esNkVEGkVgF6i3AJEJd67OP5peD9MsVuoC4dqAwY7N0eai4PkZu/yKTm22d9EfUdItijze4E/mzYYHGaCJq9iYExwqC2MorNWfUYI8ZHmYvxKy4eWo57MzAuxBOTOIAmfM/0Y2mmLG6S0SGmwSq7xVk3BJM76CdKiH0Mz6Vx54dhhisoYtLsiX+xYpWszfaQZDtzB2XP8r2DMObPF+DcaiusNNRBXFrB9FRvYCkRfNq5cGAU8EXCJkCh+dHBBEe1+cnd7eGt2iQgbNk0BSDS6Odm4W+gVE65dStA4c/XWKbq319/ep+2/iDHFOmZGSccGXJtuRLxqkfbeeQuV3IzRVlxWNEKWtDtmKMoWtDHo36i+9oyOhhL3xNPlm/RLmCgDOlGi0ZEN7B7etZjPzZ7MAcA03h6Xv53ExpzWxtLVvluucHnYV/ELqV5cFdtw2hI5zpXbI2mjO3R7F+S0pIDNkJRQxRBAD9HIg=
