version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app-lits-devops1
hooks:
  BeforeInstall:
    - location: infrastructure/AWSCodeDeploy/BeforeInstall.sh
      timeout: 30
      runas: ubuntu
  AfterInstall:
    - location: infrastructure/AWSCodeDeploy/AfterInstall.sh
      timeout: 600
      runas: ubuntu
  ApplicationStop:
    - location: infrastructure/AWSCodeDeploy/ApplicationStop.sh
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: infrastructure/AWSCodeDeploy/ApplicationStart.sh
      timeout: 30
      runas: ubuntu
  ValidateService:
    - location: infrastructure/AWSCodeDeploy/ValidateService.sh
      timeout: 30
      runas: ubuntu
